image: 'node:18.7.0'

build:
  stage: build
  variables:
    VERSION: '1.6'
  script:
  - apt-get update
  - apt-get install -y zip
  - sed -i "s/--VERSION--/$VERSION/" public/manifest.json
  - npm ci
  - npm run build-all
  - mkdir source
  - cp -r src source
  - cp -r public source
  - cp package.json source
  - cp package-lock.json source
  - cp tsconfig.json source
  - cp rollup.config.js source
  - sed -i "s/--OS_RELEASE--/$(lsb_release -a)/" README.md
  - sed -i "s/--NODE_VERSION--/$(node -v)/" README.md
  - sed -i "s/--NPM_VERSION--/$(npm -v)/" README.md
  - cp README.md source
  - cat README.md
  - zip -r "source-$VERSION.zip" source
  artifacts:
    paths:
    - artifacts/clocktrack-${VERSION}.zip
    - source-${VERSION}.zip
  only:
  - pushes
